### ISSUE TITLE
path of nested CSS url() is wrong when import uses relative path

### ISSUE THREAD

**Issue by millermedeiros** [jrburke/r.js#5]
issue when optimizing whole project and also while trying to optimize a single file.
### css/main.css

``` css
@import url('./foo/bar.css');
body{background-image:url('../img/lol_cat.jpg')}
```
### css/foo/bar.css

``` css
#bar{background-image:url('../../../img/unicorn.jpg')}
```
### css/main.css

``` css
#bar{background-image:url(./img/unicorn.jpg)}
body{background-image:url(../img/lol_cat.jpg)}
```

`#bar` background image is pointing to wrong folder.

issue only happens if `@import url` starts with a relative path ("./") - replacing first line of main.css with `@import url('foo/bar.css');` produces the desired output.
