### ISSUE TITLE
Inlining CSS from @import doesn't strip @charset

### ISSUE THREAD

**Issue by ianlewis** [jrburke/r.js#640]
When inlining css files included by an @import, the @charset declaration at the top of the imported css file are not stripped out before it is included.

So the final file is something like this:

``` css
@charset "utf-8";
. some-style {
    font-size: 12px;
}

@charset "utf-8";
.other-style {
    font-size: 10px;
}
```

It seems like the @charset should be stripped from the output file. Are there any problems with that? Is there a good way to end up with the correct end result?
