### ISSUE TITLE
CSS string containing /* gets treated as a comment

### ISSUE THREAD

**Issue by mamacdon** [jrburke/r.js#729]
Run this file through the CSS optimizer:

``` css
div:before {
  content: "hi/*";
}
.foo { color: red; } /* This is a real comment */
.bar { font-weight: bold; }
```

It produces this output:

``` css
div:before {
  content: "hi
.bar { font-weight: bold; }
```

The text between `/*` and `*/` was stripped out. If there's no `*/`, the optimizer quits with an error.

This can be worked around by escaping the slash as \002f, but it would be nice to have fixed.
